(autoload 'column-highlight-mode                "col-highlight" "" t)
(autoload 'col-highlight-toggle-when-idle       "col-highlight" "" t)
(autoload 'col-highlight-set-interval           "col-highlight" "" t)
(autoload 'col-highlight-flash                  "col-highlight" "" t)
(autoload 'col-highlight-highlight              "col-highlight" "" nil)
(autoload 'col-highlight-unhighlight            "col-highlight" "" nil)
(provide 'col-highlight-epackage-autoloads)
